apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: flux
  name: flux-test-ns
  namespace: test
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: flux
  name: flux-test-ns
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-test-ns
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: flux


