kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx
  labels:
    app: ingress-nginx-external
    system: ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=dev
spec:
  # this setting is t make sure the source IP address is preserved.
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: ingress-nginx-external
    system: ingress
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
